# action.yml
name: 'Ubuntu tests'
description: 'Run tests on Ubuntu'
inputs:
  node-version:
    description: 'Version of node'
    required: true
    default: '10'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.node-version }}
