name: Unit Tests and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:
    strategy:
      matrix:
        node: [ 16, 14, 12 ]
        platform: [ macos-latest, windows-2019 ]
    runs-on: ${{ matrix.platform }}
    name: ${{ matrix.platform }} Node ${{ matrix.node }} build/test
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Run tests
        run: |
          npm install
          npm test
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.platform }}-${{ matrix.node }}
          path: build/Release/funcinfo.node
        if: github.ref == 'refs/heads/main'
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.platform }}-${{ matrix.node }}
          path: build/Release/codeevents.node
        if: github.ref == 'refs/heads/main'


  build-and-test-linux-before-16:
    strategy:
      matrix:
        node: [ 14, 12 ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/centos7-test
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/upload-artifact@v1
        with:
          name: linux-${{ matrix.node }}
          path: build/Release/funcinfo.node
        if: github.ref == 'refs/heads/main'
      - uses: actions/upload-artifact@v1
        with:
          name: linux-${{ matrix.node }}
          path: build/Release/codeevents.node
        if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

  build-and-test-linux-16-plus:
    strategy:
      matrix:
        node: [ 16 ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/ubuntu-test
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/upload-artifact@v1
        with:
          name: linux-${{ matrix.node }}
          path: build/Release/funcinfo.node
        if: github.ref == 'refs/heads/main'
      - uses: actions/upload-artifact@v1
        with:
          name: linux-${{ matrix.node }}
          path: build/Release/codeevents.node
        if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

  artifact:
    if: github.ref == 'refs/heads/main'
    needs: [ build-and-test, build-and-test-linux-before-16, build-and-test-linux-16-plus ]
    runs-on: ubuntu-latest
    name: Building artifact
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      # download all of the built artifacts.
      - run: mkdir artifact
      - uses: actions/download-artifact@v1
        with:
          name: linux-16
          path: artifact/linux-16
      - uses: actions/download-artifact@v1
        with:
          name: linux-14
          path: artifact/linux-14
      - uses: actions/download-artifact@v1
        with:
          name: linux-12
          path: artifact/linux-12
      - uses: actions/download-artifact@v1
        with:
          name: macos-latest-16
          path: artifact/darwin-16
      - uses: actions/download-artifact@v1
        with:
          name: macos-latest-14
          path: artifact/darwin-14
      - uses: actions/download-artifact@v1
        with:
          name: macos-latest-12
          path: artifact/darwin-12
      - uses: actions/download-artifact@v1
        with:
          name: windows-2019-16
          path: artifact/win32-16
      - uses: actions/download-artifact@v1
        with:
          name: windows-2019-14
          path: artifact/win32-14
      - uses: actions/download-artifact@v1
        with:
          name: windows-2019-12
          path: artifact/win32-12
      - name: pack artifact
        run: |
          echo "artifacts" && ls artifact
          mv *.js package.json artifact/
          cd artifact && npm pack | xargs -I '{}' mv {} ./funcinfo.tgz
      - uses: actions/upload-artifact@v1
        with:
          name: funcinfo.tgz
          path: artifact/funcinfo.tgz
        # upload the un-tar'd version
      - uses: actions/upload-artifact@v1
        with:
          name: funcinfo
          path: artifact

  artifact-test:
    if: github.ref == 'refs/heads/main'
    needs: [ artifact ]
    env:
      USE_ARTIFACT: 1
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-2019 ]
        node: [ 12, 14, 16 ]
    name: ${{ matrix.platform }} Unit tests with artifact
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - uses: actions/download-artifact@v1
        with:
          name: funcinfo
          path: prebuilt
      - run: npm test
