name: Release

on:
  push:
    tags: ['*']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HUSKY: 0

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build-group: linux-x64
          - os: macos-latest
            build-group: darwin-x64+arm64
          - os: windows-2019
            build-group: win32-x64
    name: Build ${{ matrix.build-group }}
    runs-on: ${{ matrix.os }}
    env:
      BUILD_GROUP: ${{ matrix.build-group }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          architecture: x64
      - name: Install
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build:$BUILD_GROUP
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BUILD_GROUP }}
          path: prebuilds/${{ env.BUILD_GROUP }}/
          retention-days: 1
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: build
    name: Release to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org
      - name: Install
        run: npm ci --ignore-scripts
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: prebuilds/
      - name: Publish to npm
        run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
