name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HUSKY: 0

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node: [12, 14, 16, 18, 20]
        os: [ubuntu-latest, macos-latest, windows-2019]
    name: Node v${{ matrix.node }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          architecture: x64
      - name: npm
        run: echo "::set-output name=version::$(node -p "\"$(npm --version)\".split('.')[0]")"
      - name: Python version
        run: python --version
      - name: Install setuptools
        run: pip install setuptools
      - name: Update npm
        if: steps.npm.outputs.version < '8'
        run: npm install -g npm@8
      - name: Install dependencies
        run: npm ci
      - name: Show node-gyp version
        run: npm ls node-gyp
      - name: Test
        run: npm test
