name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node: [12, 14, 16]
        os: [macos-latest, windows-2019]
        include:
          - os: macos-latest
            build-group: darwin-x64+arm64
          - os: windows-2019
            build-group: win32-x64
    name: Node v${{ matrix.node }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    env:
      BUILD_GROUP: ${{ matrix.build-group }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          architecture: x64
      - name: Install
        run: npm ci
      - name: Test
        run: npm test
  test-linux:
    strategy:
      fail-fast: false
      matrix:
        node: [12, 14, 16]
        container: ['', -alpine]
    name: Node v${{ matrix.node }} (node:${{ matrix.node }}${{ matrix.container }})
    runs-on: ubuntu-latest
    container: node:${{ matrix.node }}${{ matrix.container }}
    env:
      BUILD_GROUP: linux-x64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Test
        run: npm test
