name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HUSKY: 0

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node: [16, 18, 20, 22]
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Node v${{ matrix.node }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Update npm
        run: npm install -g npm@10
      # new versions of python don't include distutils. setuptools provides it.
      - name: Install setuptools
        run: pip install setuptools
      - name: Install dependencies and build
        run: npm ci
      - name: Test
        run: npm test
